# Build and autotest script for PX4 Firmware
# http://travis-ci.org

language: cpp

git:
  depth: 2000

matrix:
  fast_finish: true
  include:
    - os: linux
      sudo: required
      services:
        - docker
      env: BUILD_TARGET=qgc_firmware
    - os: linux
      sudo: required
      services:
        - docker
      env: BUILD_TARGET=check_format
    - os: linux
      sudo: required
      services:
        - docker
      env: BUILD_TARGET=tests_linux
    - os: linux
      sudo: required
      services:
        - docker
      env: BUILD_TARGET=clang-tidy
    - os: linux
      sudo: required
      services:
        - docker
      env: BUILD_TARGET=px4_metadata

cache:
  ccache: true

before_install:
  - if [[ "${TRAVIS_OS_NAME}" = "linux" && "${TRAVIS_BRANCH}" == "coverity" ]]; then sudo apt-get install genromfs && pip install empy jinja2; fi

env:
  global:
# COVERITY KEY
    - secure: "NyaJoCGjU0Xc90Y6bxVYWLgjrJX5HlZsm/SPxruZ6I7xkGo19fJIFzGegOHQFR32D4AiKjllfjTUNy+ncckWplind0QwxtF4/kxXrz9XBfiby6X8jLYXIekrB6Ay0mBLGbniDdh+lpWtcyop6Dmkt5bdJCJuKY2nv9ENnhhs07M="
# AWS KEY: $PX4_AWS_KEY
    - secure: "XknnZHWBbpHbN4f3fuAVwUztdLIu8ej4keC3aQSDofo3uw8AFEzojfsQsN9u77ShWSIV4iYJWh9C9ALkCx7TocJ+xYjiboo10YhM9lH/8u+EXjYWG6GHS8ua0wkir+cViSxoLNaMtmcb/rPTicJecAGANxLsIHyBAgTL3fkbLSA="
# AWS SECRET: $PX4_AWS_SECRET
    - secure: "h6oajlW68dWIr+wZhO58Dv6e68dZHrBLVA6lPXZmheFQBW6Xam1HuLGA0LOW6cL9TnrAsOZ8g4goB58eMQnMEijFZKi3mhRwZhd/Xjq/ZGJOWBUrLoQHZUw2dQk5ja5vmUlKEoQnFZjDuMjx8KfX5ZMNy8A3yssWZtJYHD8c+bk="

script:
  - if [[ "${TRAVIS_BRANCH}" == "coverity" ]]; then
      echo "no script for coverity build";
    elif [[ "${BUILD_TARGET}" = "qgc_firmware" ]]; then
      ./Tools/docker_run.sh 'make qgc_firmware';
    elif [[ "${BUILD_TARGET}" = "check_format" ]]; then
      ./Tools/docker_run.sh 'make check_format';
    elif [[ "${BUILD_TARGET}" = "tests_linux" ]]; then
      ./Tools/docker_run.sh 'make tests';
    elif [[ "${BUILD_TARGET}" = "px4_metadata" ]]; then
      ./Tools/docker_run.sh 'make px4_metadata';
    elif [[ "${BUILD_TARGET}" = "clang-tidy" ]]; then
      PX4_DOCKER_REPO=px4io/px4-dev-clang:2017-04-22 ./Tools/docker_run.sh 'make clang-tidy-parallel';
    fi

after_success:
# s3 deploy individual firmware files (.px4), Firmware.zip, airframe.xml, and param.xml
  - if [[ "${BUILD_TARGET}" = "qgc_firmware" && "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" != "coverity" ]]; then
         ./Tools/docker_run.sh 'make s3put_firmware AWS_S3_BUCKET="px4-travis/archives/Firmware/${TRAVIS_BRANCH}/${TRAVIS_BUILD_ID}"'
      && ./Tools/docker_run.sh 'make s3put_qgc_firmware AWS_S3_BUCKET="px4-travis/Firmware/${TRAVIS_BRANCH}"';
    fi
  - if [[ "${BUILD_TARGET}" = "px4_metadata" && "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" != "coverity" ]]; then
         ./Tools/docker_run.sh 'make s3put_parameters_markdown AWS_S3_BUCKET="px4-travis/Firmware/${TRAVIS_BRANCH}"';
    fi

deploy:
# on tags deploy Firmware.zip to Github releases
  - provider: releases
    api_key: 
      secure: GsOINmQ/2cZ0nQ6qiR6M64CvtjT4PkJzf/ZIhU28GVbwuP91zoc+CjaQtUD2ylQx0iJ6GgbVL8y0PdofQCYotG2XXdid8Gh6jtTSmo5/c+G2FcB5lOsZWLgGsLFS0IHWt2LOb5c0pLWTibr6T9h52jbv7AdSQIYyWv6mwT9wdM4RkUrRZ9zhZv1iDlzsgrwf+RTNl9GWwiCBirSkEE1uJMGaIInRLTcni9alFOO2PwWF2/uxmWoGDjqcArtGj+Zy2imtZer/Tb4P+eXXS7xP0beTuLFSrmtw6/vfiwg6bMjGhYiDQcGj0TE0OhNTTqYZOjh121x6+jISDRvJ6w8EbCZUk/XH1rCsTMs3Hu9Ym4/BeIp7H0aReRs9G7iheV2gKKfYcoRH0NuN7U+u4YgqFilHKN/LOI3+YV0bZSGTjopEllybXyNlTgSghsNgf6G5O6uWF+iohkPoCpMKMhRUKpwjJaeZsnJznKDDamvs/fxVL3PZV8kd5TGW9cH69qH6XFkfClchqSDAW0BgtCdR8smWryqFzADuF6aPYplUHf0MRZAH+pgpL6BLgSLJpO3tauS3Jh/TIc9FhtQgn1AYh9+Y9ms6AluJfi1ycvuwNw4bfjw+7gGwP34S/jMYlDcywFV7xaGxzbyMYrPdFk7LC6bO328D49+p5k7ruQ1S2gM=
    file: "Firmware.zip"
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
      repo: sylvesterwwx/Firmware
      condition: $BUILD_TARGET = qgc_firmware

addons:
  coverity_scan:
    project:
      name: sylvesterwwx/Firmware
    notification_email: ci@px4.io
    build_command: make posix_sitl_default
    branch_pattern: coverity

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2b9c4a4cb2211f8befba
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
  slack:
    rooms:
      - secure: "QKw73Zel/s3JAbe/7XyO9tPnJwiiGFpYzSjdR8lG3tYFjRdXZnhxG4c+G7bkgkaPTS4Hult33VXE3kcEqOI7+C+eRwRlZhDfL0knQbXVCxjcLjzmUFdoPOwurlgZDw66PFWCi5tZcLKSRo3u4U8ibT4WKi3jm9sDSyOcfBAucMU="
    on_pull_requests: false
    on_success: never  # options: [always|never|change] default: always
    on_failure: never  # options: [always|never|change] default: always
